### ISSUE TITLE
Other Python wrappers

### ISSUE THREAD

**Issue by arbox** [mrkn/pycall#20]
Dear @mrkn ,

while I was looking for Ruby-Python bindings I found a less active older project: https://github.com/halostatue/rubypython

Apparently this has been updated today.

There were two other attempts to work with Python:

- https://github.com/steeve/rupy
- https://github.com/whymirror/unholy

Did you have any contact with the maintainers on these projects?

**Comment by mrkn** [comment]
Thank you for reporting.

I'd found [halostatue/rubypython](https://github.com/halostatue/rubypython) before I started to write this pycall.  And then I thought that it is good to ignore rubypython due to the following reasons.

- It was inactive for a long time at that time
- I need to support Python 3
- I think Its APIs don't match for the goal of my approach
- I want to follow [JuliaPy/PyCall.jl](https://github.com/JuliaPy/PyCall.jl)
- I want to focus on applications in data science area
- I need to move to use fiddle instead of ruby-ffi for minimal dependencies

I didn't know steeve/rupy and whymirror/unholy.  Rupy is same as rubypython, and it is inactive for a longer time than rubypython, so I don't think it has an important value.
In contrast, unholy is a transpiler approach.  I'm interested in that approach, but it is not related to PyCall.

Although I didn't contact to the maintainers of them, I don't think I need to contact them.

**Comment by arbox** [comment]
Hi @mrkn ,
thank you for your reply. It's definitely up to you if you want to contact/work with people from other related projects. My only concern was if the Ruby non-web community is tiny why not to consolidate efforts. I would at least inform those people and inform them about your work. Probably they would contribute and use PyCall. And real-world use cases are extremely important.

I wonder if you have an idea how the performance of fiddle/ffi can be compared with a native extension in case of PyCall. If I'm not mistaken the performance was the only reason why Nokogiri does not run via FFI. 

Thanks a lot for your engagement!

**Comment by mrkn** [comment]
> I would at least inform those people and inform them about your work. 

OK.  It's not problem for me.

I agreed with you about that real-world use cases are extremely important, and of course any contributions are welcome.
But it's an experimental development phase of PyCall, so it's important for me for several months that I can do anything by trial and errors.

The reason why I don't take a way of native extension for PyCall is that ffi allows us to select which libpython is used from PyCall in runtime.  This dynamic library loading is necessary for PyCall to support both Python 2 and 3 by the single installation of gem, simultaneously.  Performance is not a matter.

**Comment by arbox** [comment]
Thank you for clarifications! I'll try to support this project as far as I can.
